export const CURRENCY_SYMBOLS = {
  USD: "$",
  EUR: "€",
  MAD: "MAD",
};

export const translations = {
  en: {
    loanCalculator: "Loan Calculator",
    loanAmount: "Loan Amount",
    loanTerm: "Loan Term",
    interestRate: "Interest Rate",
    loanBreakdown: "Overview",
    monthlyPayment: "Monthly Payment",
    totalInterest: "Total Interest",
    principalAmount: "Principal Amount",
    totalPayment: "Total Payment",
    years: "Years",
    settings: "Settings",
    close: "Close",
  },
  fr: {
    loanCalculator: "Calculatrice de Prêt",
    loanAmount: "Montant du Prêt",
    loanTerm: "Durée du Prêt",
    interestRate: "Taux d'Intérêt",
    loanBreakdown: "Aperçu",
    monthlyPayment: "Paiement Mensuel",
    totalInterest: "Intérêt Total",
    principalAmount: "Montant Principal",
    totalPayment: "Paiement Total",
    years: "Années",
    settings: "Paramètres",
    close: "Fermer",
  },
  ar: {
    loanCalculator: "حاسبة القرض",
    loanAmount: "قيمة القرض",
    loanTerm: "مدة القرض",
    interestRate: "نسبة الفائدة",
    loanBreakdown: "نظرة عامة",
    monthlyPayment: "الدفع الشهري",
    totalInterest: "إجمالي الفائدة",
    principalAmount: "المبلغ الأساسي",
    totalPayment: "المبلغ الإجمالي",
    years: "سنوات",
    settings: "الإعدادات",
    close: "إغلاق",
  },
};
